- nodeset:
    name: emea-node
    nodes:
      - name: node
        label: ubuntu-bionic
- nodeset:
    name: nafta-node
    nodes:
      - name: node2
        label: centos76
        
- job:
    name: demomavenbuildjob
    run: playbooks/demomavenbuild.yaml
    parent: base
    
- job:
    name: applylabel_emea
    run: playbooks/applylabel_emea.yaml   (get the user and check if he is part of the emea region)
    parent: base
    nodeset:
      nodes:
        - name: node
          label: centos76
- job:
    name: applylabel_nafta
    run: playbooks/applylabel_mafta.yaml   (get the user and check if he is part of the emea region)
    parent: base
    nodeset:
      nodes:
        - name: node
          label: centos76

		  
- project:
    checklabel_emea:
      jobs:
        - applylabel_emea
	checklabel_nafta:
	  jobs:
	    - applylabel_nafta
	check_emea:
      jobs:
       - demomavenbuildjob:
           nodeset: emea-node
    check_nafta:
      jobs:
       - demomavenbuildjob:
           nodeset: nafta-node
