- nodeset:
    name: ubuntu-bionic
    nodes:
      - name: node
        label: ubuntu-bionic
- nodeset:
    name: centos76
    nodes:
      - name: node2
        label: centos76
        
- job:
    name: demomavenbuildjob
    run: playbooks/demomavenbuild.yaml
    parent: base
    
- project:
    region1:
      jobs:
       - demomavenbuildjob:
           nodeset: ubuntu-bionic
    region2:
      jobs:
       - demomavenbuildjob:
           nodeset: centos76
