- nodeset:
    name: ubuntu-bionic
    nodes:
      - name: node
        label: ubuntu-bionic
- nodeset:
    name: centos76
    nodes:
      - name: node2
        label: centos76
        
- job:
    name: demomavenbuildjob
    run: playbooks/demomavenbuild.yaml
    parent: base
    
- project:
    regionEMEA:
      jobs:
       - demomavenbuildjob:
           nodeset: ubuntu-bionic
    regionNAFTA:
      jobs:
       - demomavenbuildjob:
           nodeset: centos76
