- hosts: all
  tasks:
    - debug:
        msg: "running for gameof life demo"
        
    - name: "Deleted the workspace dir before build"
      shell: |
            rm -rf ~/work
      register: clean_output
      
    - name: Clone git repo
      git:
        repo: https://github.com/zuul-hcl-org/gameoflife.git
        dest: ~/work/
      when: clean_output is succeeded
      
    - name: Build sample project
      shell: |
            /opt/maven/apache-maven-3.5.4/bin/mvn -f ~/work/pom.xml clean install
      register: output
      
    - name: Push artifacts to jfrog repository
      uri:
        url: http://172.31.27.120:9081/artifactory/generic-local/gameoflife.war
        validate_certs: no
        method: PUT
        headers:
          X-JFrog-Art-Api: AKCp5dK4mF6tBdrReiknVmQ8X6zBp6SstMM34jzu6NkfMecn2MQEbh2jp2ma8kKSw3JVybbWP
        src: ~/work/gameoflife-web/target/gameoflife.war
        status_code: 201
        remote_src: yes
