- hosts: all
  tasks:
    - debug:
        msg: "running for gameof life demo"
        
    - name: "Deleted the workspace dir before build"
      shell: |
            rm -rf ~/work
      register: clean_output
      
    - name: Clone git repo
      git:
        repo: https://github.com/zuul-hcl-org/gameoflife.git
        dest: ~/work/
      when: clean_output is succeeded
      
    - name: Build sample project
      shell: |
            /opt/maven/apache-maven-3.5.4/bin/mvn -f ~/work/pom.xml clean install
      register: output
      
    - name: Push artifacts to jfrog repository
      uri:
        url: http://172.31.27.120:9081/artifactory/generic-local/gameoflife.war
        validate_certs: no
        method: PUT
        headers:
          X-JFrog-Art-Api: AKCp5dK4un9rhNwegiiRP2GNEWijqzYYbxoawz6QzHVFuU5VWpGGXdzaTSV5eLEpoan64FpQW
        src: ~/work/gameoflife-web/target/gameoflife.war
        status_code: 201
        remote_src: yes
    - debug:
       msg: "this is shiva {{ zuul.change_url }}"
    - shell: |
         echo {{ zuul.change_url }} | cut -d '/' -f 7
      register: pullid
    - debug:
       msg: "{{ shiva kumar pullid }}"
  
